# Generated by Django 5.1.7 on 2025-07-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "issue",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("cleaning", "Cleaning"),
                            ("teaching", "Teaching"),
                            ("technical", "Technical Support"),
                            ("medical", "Medical"),
                            ("electrical", "Electrical"),
                            ("carpentry", "Carpentry"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_issue",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField()),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
