# Generated by Django 5.1.7 on 2025-07-27 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "issue",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("cleaning", "Cleaning"),
                            ("teaching", "Teaching"),
                            ("technical", "Technical Support"),
                            ("medical", "Medical"),
                            ("electrical", "Electrical"),
                            ("carpentry", "Carpentry"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_issue",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField()),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=15, unique=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, default="India", max_length=100, null=True
                    ),
                ),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("expected_time", models.DateTimeField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, null=True, upload_to="appointment_images/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProviderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "profile_photo",
                    models.ImageField(upload_to="service_providers/profile_photos/"),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "alternate_number",
                    models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "aadhar_number",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(12),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                    ),
                ),
                (
                    "service_provider_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Preference1",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("cleaning", "Cleaning"),
                            ("teaching", "Teaching"),
                            ("technical", "Technical Support"),
                            ("medical", "Medical"),
                            ("electrical", "Electrical"),
                            ("carpentry", "Carpentry"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "other_preference1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "Preference2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("cleaning", "Cleaning"),
                            ("teaching", "Teaching"),
                            ("technical", "Technical Support"),
                            ("medical", "Medical"),
                            ("electrical", "Electrical"),
                            ("carpentry", "Carpentry"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "other_preference2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProviderBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(10),
                        ],
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.MinLengthValidator(9),
                            django.core.validators.MaxLengthValidator(18),
                        ],
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                (
                    "ifsc_code",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            django.core.validators.MaxLengthValidator(11),
                        ],
                    ),
                ),
                ("upi_id", models.CharField(max_length=50)),
                (
                    "upi_mobile_number",
                    models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="skill.serviceproviderdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInitialRegistrationPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.PositiveIntegerField()),
                ("payment_date", models.DateField(auto_now_add=True)),
                ("payment_proof", models.ImageField(upload_to="payments/")),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="skill.serviceproviderdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bargaining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "servicer_offer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "user_offer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("user_accepted", "User Accepted"),
                            ("servicer_accepted", "Servicer Accepted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "offered_by",
                    models.CharField(
                        choices=[("user", "User"), ("servicer", "Servicer")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargains",
                        to="skill.book_appointment",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skill.serviceproviderdetails",
                    ),
                ),
            ],
        ),
    ]
