# Generated by Django 5.1.7 on 2025-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_book_appointment_serviceproviderdetails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="Preference1",
            field=models.CharField(
                choices=[
                    ("plumbing", "Plumbing"),
                    ("cleaning", "Cleaning"),
                    ("teaching", "Teaching"),
                    ("technical", "Technical Support"),
                    ("medical", "Medical"),
                    ("electrical", "Electrical"),
                    ("carpentry", "Carpentry"),
                    ("others", "Others"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="Preference2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plumbing", "Plumbing"),
                    ("cleaning", "Cleaning"),
                    ("teaching", "Teaching"),
                    ("technical", "Technical Support"),
                    ("medical", "Medical"),
                    ("electrical", "Electrical"),
                    ("carpentry", "Carpentry"),
                    ("others", "Others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
