# Generated by Django 5.1.7 on 2025-07-24 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_book_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_appointment",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="country",
            field=models.CharField(
                blank=True, default="India", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="ServiceProviderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_providers/profile_photos/",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "alternate_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "aadhar_number",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(12),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                    ),
                ),
                (
                    "service_provider_id",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProviderBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(10),
                        ],
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        max_length=18,
                        validators=[
                            django.core.validators.MinLengthValidator(9),
                            django.core.validators.MaxLengthValidator(18),
                        ],
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                (
                    "ifsc_code",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            django.core.validators.MaxLengthValidator(11),
                        ],
                    ),
                ),
                ("upi_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "upi_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="skill.serviceproviderdetails",
                    ),
                ),
            ],
        ),
    ]
