# Generated by Django 5.1.7 on 2025-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0003_book_appointment_address_book_appointment_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceproviderdetails",
            name="service_provider_id",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
