# Generated by Django 5.1.7 on 2025-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0003_serviceproviderdetails_preference1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="other_preference1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="other_preference2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="serviceproviderdetails",
            name="Preference1",
            field=models.CharField(
                choices=[
                    ("plumbing", "Plumbing"),
                    ("cleaning", "Cleaning"),
                    ("teaching", "Teaching"),
                    ("technical", "Technical Support"),
                    ("medical", "Medical"),
                    ("electrical", "Electrical"),
                    ("carpentry", "Carpentry"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
