# Generated by Django 5.1.7 on 2025-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0003_book_appointment_distance_km_book_appointment_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_appointment",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="Servicer Rating (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="num_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
