# Generated by Django 5.1.7 on 2025-07-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0004_serviceproviderdetails_other_preference1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book_appointment",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="book_appointment",
            name="longitude",
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="expected_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
