# Generated by Django 5.1.7 on 2025-07-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0004_book_appointment_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceproviderdetails",
            name="bookmarked_appointments",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_by_servicers",
                to="skill.book_appointment",
            ),
        ),
    ]
