# Generated by Django 5.1.7 on 2026-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0005_serviceproviderdetails_bookmarked_appointments"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_appointment",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="payout_status",
            field=models.CharField(
                choices=[("pending", "Pending Payout"), ("paid", "Paid/Settled")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="payout_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
