# Generated by Django 5.1.7 on 2025-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0005_remove_book_appointment_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_appointment",
            name="full_name",
            field=models.CharField(default="exit", max_length=100),
            preserve_default=False,
        ),
    ]
