# Generated by Django 5.1.7 on 2025-07-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0006_book_appointment_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_appointment",
            name="booking_id",
            field=models.CharField(
                default="null", editable=False, max_length=15, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book_appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
