# Generated by Django 5.1.7 on 2025-07-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0007_book_appointment_booking_id_book_appointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bargaining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original price quoted in the appointment",
                        max_digits=10,
                    ),
                ),
                (
                    "user_offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price offered by the user",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "servicer_offer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price offered by the service provider",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current negotiated price",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted_by_user", "Accepted by User"),
                            ("accepted_by_servicer", "Accepted by Servicer"),
                            ("rejected", "Rejected"),
                            ("counter_offer", "Counter Offer"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "last_updated_by",
                    models.CharField(
                        blank=True,
                        choices=[("user", "User"), ("servicer", "Servicer")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "expiry_time",
                    models.DateTimeField(
                        help_text="Time until which this offer is valid"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargaining_requests",
                        to="skill.book_appointment",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargaining_requests",
                        to="skill.serviceproviderdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargaining_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Negotiation",
                "verbose_name_plural": "Price Negotiations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BargainingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_by",
                    models.CharField(
                        choices=[("user", "User"), ("servicer", "Servicer")],
                        max_length=10,
                    ),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bargaining",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="skill.bargaining",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
