# Generated by Django 5.1.7 on 2025-07-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0008_bargaining_bargaininghistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bargaining",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="bargaining",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="bargaining",
            name="expiry_time",
        ),
        migrations.RemoveField(
            model_name="bargaining",
            name="last_updated_by",
        ),
        migrations.RemoveField(
            model_name="bargaining",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bargaining",
            name="user_offer_price",
        ),
        migrations.AddField(
            model_name="bargaining",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bargaining",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains",
                to="skill.book_appointment",
            ),
        ),
        migrations.AlterField(
            model_name="bargaining",
            name="initial_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bargaining",
            name="service_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="skill.serviceproviderdetails",
            ),
        ),
        migrations.AlterField(
            model_name="bargaining",
            name="servicer_offer_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bargaining",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("counter", "Counter Offer"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
