# Generated by Django 5.1.7 on 2025-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0009_alter_bargaining_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bargaining",
            options={},
        ),
        migrations.AddField(
            model_name="bargaining",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bargaining",
            name="user_offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
